### ISSUE TITLE
Signup page for users

### ISSUE THREAD

**Issue by redknitin** [redknitin/Helpdesk#16]
Users need a signup page.

A lot of the code can be used from the user management page.

**Comment by mohan-mu** [comment]
@redknitin i would like to contribute . can you please guide me?

**Comment by redknitin** [comment]
Hello @mohan-mu !

It's nice to hear from you.

As a first step, you can try to get the application running on your computer. There are 2 ways to do this:

**Method 1**. Install [Ruby](https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-2.4.2-2/rubyinstaller-2.4.2-2-x64.exe) and [MongoDB](https://www.mongodb.com/dr/fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.4.10-signed.msi/download) - it runs natively on your computer . Then, execute "runme.bat"

**Method 2.** Install [Oracle VirtualBox 5.1](http://download.virtualbox.org/virtualbox/5.1.30/VirtualBox-5.1.30-118389-Win.exe) and [Vagrant](https://releases.hashicorp.com/vagrant/2.0.0/vagrant_2.0.0_x86_64.msi) - it sets up a virtual machine. Then, from the project directory, run the command "vagrant up"

This should get the server running and you can access the application from your web browser at: [http://localhost:8000/](http://localhost:8000/)

**Comment by redknitin** [comment]
User signup has been implemented in ed2460a28cd5f5d3edf047bd3424fe0a1aca7583
