### ISSUE TITLE
Prevent Duplicate Email Addresses

### ISSUE THREAD

**Issue by redknitin** [redknitin/Helpdesk#19]
### Expected Behavior

When creating or updating a user, the system should check if the email address already exists in the system.

### Actual Behavior

The system accepts any email address, even if it already exists in the system

### Steps to Reproduce

From the user administration page, create a user with the email address of an existing user

**Comment by kvsm** [comment]
Working on this.

**Comment by redknitin** [comment]
Hi @kvsm !

It's good to have you on-board.

Take a look at the code at:
https://github.com/redknitin/Helpdesk/blob/a49225f119ad380f0d70e7464472f31fc7c407d8/routes/usermgt.rb#L154
This is the duplicate check for the user signup page.

Users can change their email addresses from:
1. User management page: /user-detail/&lt;username&gt;
2. User profile page: /userprofile

These pages would need a check to ensure that when the email address is being changed, the new email address doesn't exist for any other user i.e. something like `db.getCollection('users').find({'username': {'$ne': '<username>'}, 'email': 'something@somewhere.com'}).count()`

**Comment by redknitin** [comment]
@kvsm , you rock!!!

We've just merged the pull request
